"""empty message

Revision ID: 26544f4658bf
Revises: 3d63f0251bad
Create Date: 2025-04-17 14:28:50.302060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26544f4658bf'
down_revision = '3d63f0251bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('isSuperAdmin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_column('isSuperAdmin')
        batch_op.drop_column('role')
        batch_op.drop_column('isActive')
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('isActive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('isSuperAdmin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('type')

    op.drop_table('admins')
    # ### end Alembic commands ###
