"""empty message

Revision ID: 7f0816104eef
Revises: 
Create Date: 2025-04-17 13:03:09.786026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision = '7f0816104eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('roleId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('roleId')
    )
    op.create_table('sessions',
    sa.Column('sessionId', sa.String(length=36), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('ipAddress', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('sessionId')
    )
    op.create_table('users',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('isSuperAdmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    op.drop_table('users')
    op.drop_table('sessions')
    op.drop_table('roles')
    # ### end Alembic commands ###
