"""empty message

Revision ID: 828ef3292d57
Revises: a735259cee79
Create Date: 2025-04-18 15:12:49.564390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '828ef3292d57'
down_revision = 'a735259cee79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.alter_column('query',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.alter_column('query',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
