"""empty message

Revision ID: a735259cee79
Revises: 26544f4658bf
Create Date: 2025-04-18 14:49:23.854155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a735259cee79'
down_revision = '26544f4658bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('query',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint('search_history_ibfk_1', type_='foreignkey')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', mysql.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('createdAt', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key('search_history_ibfk_1', 'users', ['userId'], ['userId'])
        batch_op.alter_column('query',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
